# Generated by Django 4.0 on 2022-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=2500)),
            ],
        ),
        migrations.RenameField(
            model_name='exam1',
            old_name='Authority',
            new_name='Exam_Authority',
        ),
        migrations.RenameField(
            model_name='exam1',
            old_name='Exam',
            new_name='Exam_Name',
        ),
        migrations.RenameField(
            model_name='exam1',
            old_name='Regno',
            new_name='Register_No',
        ),
        migrations.RenameField(
            model_name='exam1',
            old_name='YearofPassing',
            new_name='Year_Of_Passing',
        ),
        migrations.RenameField(
            model_name='exam2',
            old_name='Authority',
            new_name='Exam_Authority',
        ),
        migrations.RenameField(
            model_name='exam2',
            old_name='Exam',
            new_name='Exam_Name',
        ),
        migrations.RenameField(
            model_name='exam2',
            old_name='Regno',
            new_name='Register_No',
        ),
        migrations.RenameField(
            model_name='exam2',
            old_name='YearofPassing',
            new_name='Year_Of_Passing',
        ),
        migrations.RenameField(
            model_name='exam3',
            old_name='Authority',
            new_name='Exam_Authority',
        ),
        migrations.RenameField(
            model_name='exam3',
            old_name='Exam',
            new_name='Exam_Name',
        ),
        migrations.RenameField(
            model_name='exam3',
            old_name='Regno',
            new_name='Register_No',
        ),
        migrations.RenameField(
            model_name='exam3',
            old_name='YearofPassing',
            new_name='Year_Of_Passing',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Father',
            new_name='Applicants_Name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Branch',
            new_name='Branch_Of_Study',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Name',
            new_name='Fathers_Name',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='Number',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='Batch',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2500),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Email',
            field=models.EmailField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Non-Indian', 'Non-Indian')], default='Indian', max_length=2500),
        ),
    ]
