# Generated by Django 4.0 on 2022-01-17 11:32

import WEBSITE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0002_certgen_rename_authority_exam1_exam_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='Mobile_Number',
            field=models.IntegerField(default=0, validators=[WEBSITE.models.validate_mobile]),
        ),
    ]
