# Generated by Django 4.0 on 2022-01-17 15:19

import WEBSITE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0003_registermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='College',
            field=models.CharField(default='TKM COLLEGE OF ENGINEERING,KOLLAM', max_length=2500),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Mobile_Number',
            field=models.PositiveBigIntegerField(default=0, validators=[WEBSITE.models.validate_mobile]),
        ),
    ]
