# Generated by Django 4.0 on 2022-01-17 15:20

import WEBSITE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0004_alter_registermodel_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='Mobile_Number',
            field=models.PositiveBigIntegerField(validators=[WEBSITE.models.validate_mobile]),
        ),
    ]
