# Generated by Django 4.0 on 2022-01-18 04:21

import WEBSITE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0005_alter_registermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certgen',
            name='Username',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam1',
            name='Exam_Authority',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam1',
            name='Exam_Name',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam1',
            name='Register_No',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam1',
            name='Year_Of_Passing',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam2',
            name='Exam_Authority',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam2',
            name='Exam_Name',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam2',
            name='Register_No',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam2',
            name='Year_Of_Passing',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam3',
            name='Exam_Authority',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam3',
            name='Exam_Name',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam3',
            name='Register_No',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='exam3',
            name='Year_Of_Passing',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Applicants_Name',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='College',
            field=models.CharField(default='TKM COLLEGE OF ENGINEERING,KOLLAM', max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Fathers_Name',
            field=models.CharField(max_length=2500, validators=[WEBSITE.models.validate_chara]),
        ),
    ]
