# Generated by Django 4.0 on 2022-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0006_alter_certgen_username_alter_exam1_exam_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='College',
            field=models.CharField(default='TKM COLLEGE OF ENGINEERING,KOLLAM', max_length=2500),
        ),
    ]
